.\" Title: vrc-freeze
.\" Author: vrc contributors
.\" Manual section: 1
.\"
.TH VRL\-FREEZE 1 "2025" "vrc" "User Commands"

.SH NAME
vrc\-freeze \- suspend a command in a running instance via SIGSTOP

.SH SYNOPSIS
.B vrc
\fBfreeze\fR \fIPID\fR [\fB\-c\fR \fICOMMAND\fR] [\fB\-i\fR, \fB\-\-interactive\fR]

.SH DESCRIPTION
Freeze (suspend) a running command by sending it SIGSTOP. The command's OS process is paused but not terminated; all its state is preserved in memory. Use \fBvrc thaw\fR to resume execution.

Connects to the target instance's UDS control socket at \fB~/.local/share/vrc/control\-{pid}.sock\fR and sends the freeze request.

Freezing is useful for temporarily suspending resource-intensive tasks (compilations, data processing) without losing their progress. The frozen command remains in the instance's command list and is visible via \fBvrc list\fR.

.SH ARGUMENTS

.TP
.B PID
OS process ID of the target vrc instance.

.SH OPTIONS

.TP
.BR \-c ", " \-\-command " " \fICOMMAND\fR
ID of the target command (omit for the first/only command).

.TP
.BR \-i ", " \-\-interactive
Present a numbered list of all running commands in the instance and allow the user to select one or more by number (space-separated). Only running (non-frozen) commands are shown.

.TP
.BR \-h ", " \-\-help
Print help information and exit.

.SH EXAMPLES

.PP
Freeze the only command:
.RS
.PP
.nf
\fB$ vrc freeze 12345\fR
Command cmd_abc frozen (SIGSTOP)
.fi
.RE

.PP
Freeze a specific command:
.RS
.PP
.nf
\fB$ vrc freeze 12345 \-c cmd_abc\fR
.fi
.RE

.PP
Interactively select commands to freeze:
.RS
.PP
.nf
\fB$ vrc freeze 12345 \-\-interactive\fR
  1) cargo build (PID 5678) - running
  2) htop (PID 5679) - running
Select [space-separated numbers]: 1
Command cmd_abc frozen (SIGSTOP)
.fi
.RE

.SH EXIT STATUS

.TP
.B 0
Command frozen successfully.

.TP
.B 1
Error (instance not found, command not found, etc.).

.SH SEE ALSO
.BR vrc (1),
.BR vrc\-thaw (1),
.BR vrc\-stop (1),
.BR vrc\-list (1),
.BR kill (1)
