.\" Title: vrc-stop
.\" Author: vrc contributors
.\" Manual section: 1
.\"
.TH VRC\-STOP 1 "2025" "vrc" "User Commands"

.SH NAME
vrc stop \- stop a running vrc instance

.SH SYNOPSIS
.B vrc
\fBstop\fR [\fIPID\fR] [\fB\-i\fR, \fB\-\-interactive\fR]

.SH DESCRIPTION
Sends SIGTERM to a running vrc instance to gracefully shut it down. If no PID is specified and exactly one instance is running, that instance is stopped automatically.

.SH ARGUMENTS

.TP
.B PID
Process ID of the vrc instance to stop. If omitted and exactly one instance is running, it is stopped automatically. If omitted and multiple instances are running, a list is displayed.

.SH OPTIONS

.TP
.BR \-i ", " \-\-interactive
Present a numbered list of running instances and let the user select
which ones to stop by typing space-separated numbers (e.g. "1 3 5").
Requires a terminal (stdin must be a TTY).

.SH EXAMPLES

Stop a specific instance:
.RS
.PP
.nf
\fB$ vrc stop 12345\fR
Sent SIGTERM to vrc instance (PID 12345)
.fi
.RE

Stop the only running instance:
.RS
.PP
.nf
\fB$ vrc stop\fR
.fi
.RE

.SH SEE ALSO
.BR vrc (1),
.BR vrc\-list (1)
