.\" Title: vrl-stop
.\" Author: vrl contributors
.\" Manual section: 1
.\"
.TH VRL\-STOP 1 "2025" "vrl" "User Commands"

.SH NAME
vrl stop \- stop a running vrl instance

.SH SYNOPSIS
.B vrl
\fBstop\fR [\fIPID\fR]

.SH DESCRIPTION
Sends SIGTERM to a running vrl instance to gracefully shut it down. If no PID is specified and exactly one instance is running, that instance is stopped automatically.

.SH ARGUMENTS

.TP
.B PID
Process ID of the vrl instance to stop. If omitted and exactly one instance is running, it is stopped automatically. If omitted and multiple instances are running, a list is displayed.

.SH EXAMPLES

Stop a specific instance:
.RS
.PP
.nf
\fB$ vrl stop 12345\fR
Sent SIGTERM to vrl instance (PID 12345)
.fi
.RE

Stop the only running instance:
.RS
.PP
.nf
\fB$ vrl stop\fR
.fi
.RE

.SH SEE ALSO
.BR vrl (1),
.BR vrl\-list (1)
