[book]
title = "vrunner Documentation"
authors = ["vrunner contributors"]
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "dark"
preferred-dark-theme = "dark"
preferred-light-theme = "light"
git-repository-url = "https://github.com/nkh/K"
edit-url-template = "https://github.com/nkh/K/edit/main/docs/{path}"

[output.html.print]
enable = true
